name: build test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print directory
      - run: ls -al
      - name: run setup
      - run: . .${PWD}/dev-setup.sh
